### ISSUE TITLE
Pick up the name of the output file from the input config file

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/GridIn#2]
Currently hard-coded at https://github.com/cp3-llbb/GridIn/blob/master/python/default_crab_config.py#L23

it should be overwritten by the input config file if the case happen

**Comment by blinkseb** [comment]
Actually, if we switch to CMSSW, disabling https://github.com/cp3-llbb/GridIn/blob/master/python/default_crab_config.py#L20 should be enough.

For the python framework, the output file is forced to be 'output.root' no matter what the user set in the configuration file :smile:

**Comment by OlivierBondu** [comment]
ah! correct, I did not read the crab config options deep enough, closing this then !

**Comment by OlivierBondu** [comment]
well actually reopening this: according to documentation output is automatically picked up if produced with 'PoolOutputModule or TFileService', which is not the case at the moment: https://github.com/cp3-llbb/Framework/blob/master/test/TestConfiguration.py#L37 ...

**Comment by blinkseb** [comment]
The plan is to use internally a TFileService for managing the output file. I let this open until it's done.
