### ISSUE TITLE
Crash when running runPostCrab

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/GridIn#28]
Hi,

I got this problem when running runPostCrab on _/home/fynu/swertz/scratch/CMSSW_7_4_10/src/cp3_llbb/GridIn/test/crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8_25ns.py_. 
Crab output is in _/storage/data/cms/store/user/swertz/TT_TuneCUETP8M1_13TeV-powheg-pythia8/TT_TuneCUETP8M1_13TeV-powheg-pythia8_25ns/150923_133812/0000/_.

```
##### Get information out of the crab config file (work area, dataset, pset)
done
##### Check if the dataset exists in the database
True
##### Get info from crab (logs, outputs, report)
done
##### Check if the job processed the whole sample
done
##### Figure out the code(s) version
FWUrl= https://github.com/swertz/Framework/tree/cb910ff
AnaUrl= https://github.com/swertz/TTAnalysis/tree/a6a226f
##### Figure out the number of selected events
Traceback (most recent call last):
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/runPostCrab.py", line 288, in <module>
    main()
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/runPostCrab.py", line 223, in main
    nselected  += int(line.split()[3])
ValueError: invalid literal for int() with base 10: 'method'
```

I ran the same code on another sample a couple of hours ago without problems...

I added something to the script to catch the exception and print the file name where it happens:
_/storage/data/cms/store/user/swertz/TT_TuneCUETP8M1_13TeV-powheg-pythia8/TT_TuneCUETP8M1_13TeV-powheg-pythia8_25ns/150923_133812/0000/failed/log/cmsRun_41.log.tar.gz_
As well as the line in the file causing the problem:
   _[3] Calling produce method for unscheduled module PATJetSelector/'selectedPatJetsAK4PFCHS'_

I haven't checked out the code of runPostCrab yet... Why is it looking at the output of failed jobs? In this case a segfault happened and I had to resubmit it manually. It then finished successfully, see _/storage/data/cms/store/user/swertz/TT_TuneCUETP8M1_13TeV-powheg-pythia8/TT_TuneCUETP8M1_13TeV-powheg-pythia8_25ns/150923_133812/0000/log/cmsRun_41.log.tar.gz_

**Comment by blinkseb** [comment]
It seems like `crab getlog` returns also the logs of failed jobs. We are currently working on the database to avoid this kind of issues, but for the mean time, I guess we can just avoid processing logs with `failed` in their path.

**Comment by swertz** [comment]
Ok, should I just insert a check that `failed` is not in the path here: https://github.com/cp3-llbb/GridIn/blob/master/scripts/runPostCrab.py#L217 for the time being?

**Comment by blinkseb** [comment]
I guess it should do the trick yeah. Or maybe the getlog option has an option for not including failed jobs?

**Comment by swertz** [comment]
`crab getlog --help` doesn't show anything that would help...
