### ISSUE TITLE
Add analyzer name in the sample name string

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/GridIn#30]
so that we can browse more easily which samples are useful for each individual

any objection ?

**Comment by swertz** [comment]
Ok with me

**Comment by AlexandreMertens** [comment]
no objections, good idea!

**Comment by blinkseb** [comment]
Sounds good. Just a question, how do you get the analyzer name?

**Comment by OlivierBondu** [comment]
same way it's already done for fetching the github urls: 
https://github.com/cp3-llbb/GridIn/blob/master/scripts/runPostCrab.py#L57-L61

(possibly stripping any 'Analysis' at the end ?)

**Comment by blinkseb** [comment]
Ok so it's basically the git repository name in which the python configuration file is, right?

**Comment by OlivierBondu** [comment]
yes indeed :)

**Comment by blinkseb** [comment]
Perfect :)
