### ISSUE TITLE
Automatic analyzer configuration of data / mc

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/GridIn#48]
We like having only [one config file](https://github.com/cp3-llbb/HHAnalysis/blob/master/test/HHConfiguration.py) containing a switch `runOnData` instead of maintaining two configs, [one for data](https://github.com/cp3-llbb/Framework/blob/CMSSW_7_4_12p/test/TestConfigurationData.py) and [one for mc](https://github.com/cp3-llbb/Framework/blob/CMSSW_7_4_12p/test/TestConfigurationMC.py). However this is a bit cumbersome to edit depending what we are launching on crab

The fix would be to have `runOnGrid.py` detect `runOnData` in the configuration file and switch it on or off depending on the `--mc` or `--data` flag passed to it. This would avoid `runPostCrab.py` saying the git repo is dirty, while technically it is a one-line change not intended to be committed/pushed.

(this feature is not necessarily wanted 'centrally', so by default is assigned to an HH analyser I guess :smile: )

**Comment by blinkseb** [comment]
I think the correct way to handle this is like we do for everything else, a command-line flag `isData` or `isMC` which overrides the argument passed to the `create` function.
