### ISSUE TITLE
DoubleEG Re-reco

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/GridIn#62]
See https://indico.cern.ch/event/472017/contribution/0/attachments/1206049/1757467/15-12-16_News_PPD.pdf: there's been a reprocessing of run2015D DoubleEG & SingleElectron datasets with a new ECAL calibration.
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2F*%2F*2015D*04Dec2015*%2F*+status%3D*
(post-it to remember it for the next prod)

**Comment by OlivierBondu** [comment]
I'm not sure if we want it if it's only for EG datasets... ?

**Comment by swertz** [comment]
We use DoubleEG right?

What I don't understand is why there's no impact on MuonEG, for instance...

**Comment by OlivierBondu** [comment]
I think the intent of this rereco is intended for ECAL/Egamma calibration and other checks... In any case, we're "likely" to switch to 76X MC and 76X end-of-the-year data rereco (injection planned today or tomorrow) which are supposed to be the main datasets for use for Moriond analyses.

**Comment by swertz** [comment]
Oh, OK! I was hoping this would solve the shift in the Z peak we see in ee, but we'll just wait a bit then...

Yes; certification of the 76X re-reco is planned for end of january.
